apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
    annotations:
        openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2024-01-31T19:05:09Z"
    generation: 4
    labels:
        app: httpd-teste6
    name: httpd-teste6
    namespace: paas-hml
    resourceVersion: "540127022"
    uid: bea1574d-89e4-4a23-a84e-45250966e0f9
spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        app: httpd-teste6
        deploymentconfig: httpd-teste6
    strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
            intervalSeconds: 1
            maxSurge: 25%
            maxUnavailable: 25%
            timeoutSeconds: 600
            updatePeriodSeconds: 1
        type: Rolling
    template:
        metadata:
            annotations:
                openshift.io/generated-by: OpenShiftNewApp
            creationTimestamp: null
            labels:
                app: httpd-teste6
                deploymentconfig: httpd-teste6
        spec:
            containers:
                - image: image-registry.openshift-image-registry.svc:5000/paas-hml/httpd-teste6@sha256:212f61a91651b44e8beb9635885deaae57c8b15a8a50716dd7cebb9a6457b4be
                  imagePullPolicy: Always
                  name: httpd-teste6
                  ports:
                    - containerPort: 8443
                      protocol: TCP
                    - containerPort: 8080
                      protocol: TCP
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /srv/data
                      name: httpd-teste6-001
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - name: httpd-teste6-001
                  persistentVolumeClaim:
                    claimName: httpd-teste6-001
    test: false
    triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
                - httpd-teste6
            from:
                kind: ImageStreamTag
                name: httpd-teste6:latest
                namespace: paas-hml
            lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/paas-hml/httpd-teste6@sha256:212f61a91651b44e8beb9635885deaae57c8b15a8a50716dd7cebb9a6457b4be
          type: ImageChange
status:
    availableReplicas: 0
    conditions:
        - lastTransitionTime: "2024-01-31T19:05:09Z"
          lastUpdateTime: "2024-01-31T19:05:09Z"
          message: Deployment config does not have minimum availability.
          status: "False"
          type: Available
        - lastTransitionTime: "2024-08-29T13:46:18Z"
          lastUpdateTime: "2024-08-29T13:46:18Z"
          message: replication controller "httpd-teste6-3" has failed progressing
          reason: ProgressDeadlineExceeded
          status: "False"
          type: Progressing
    details:
        causes:
            - type: Manual
        message: manual change
    latestVersion: 3
    observedGeneration: 4
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
