### Variables
@urlBase = http://localhost:3000

### Get users
GET {{urlBase}}/users HTTP/1.1

### Insert user
POST {{urlBase}}/users HTTP/1.1
Content-Type: application/json

{
  "id":     1,
  "name":   "John",
  "email":  "j@j.com"
}

